[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_escrow = "B3G5V8XLTyXVpM8txNJgdezuCJZrVq4y4zD1aVzezEvw"

[programs.devnet]
solana_escrow = "B3G5V8XLTyXVpM8txNJgdezuCJZrVq4y4zD1aVzezEvw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
