[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_escrow = "3SgbiXdLJ81n1r5HR42fbHGWfQM3Djds6kfyYPeNQUKs"

[programs.localnet]
solana_escrow = "3SgbiXdLJ81n1r5HR42fbHGWfQM3Djds6kfyYPeNQUKs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
