[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_escrow = "BavkK9zHbyor4hkWNNj14GT3WqxmQw3vKLR9TumKW1wh"

[programs.localnet]
solana_escrow = "BavkK9zHbyor4hkWNNj14GT3WqxmQw3vKLR9TumKW1wh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
